# Generated by Django 4.2.30 on 2026-06-29 10:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=15)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('driver_id', models.CharField(blank=True, max_length=10, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=15)),
                ('license_number', models.CharField(max_length=50, unique=True)),
                ('vehicle_number', models.CharField(max_length=20, unique=True)),
                ('vehicle_type', models.CharField(choices=[('sedan', 'Sedan (4 Seater)'), ('suv', 'SUV (6 Seater)'), ('tempo', 'Tempo Traveller (12 Seater)')], max_length=20)),
                ('vehicle_model', models.CharField(max_length=100)),
                ('is_available', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('current_lat', models.FloatField(blank=True, null=True)),
                ('current_lng', models.FloatField(blank=True, null=True)),
                ('last_location_update', models.DateTimeField(blank=True, null=True)),
                ('joined_date', models.DateField(default=django.utils.timezone.now)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='driver', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_id', models.CharField(blank=True, max_length=20, unique=True)),
                ('customer_name', models.CharField(max_length=100)),
                ('customer_phone', models.CharField(max_length=15)),
                ('customer_email', models.EmailField(blank=True, max_length=254)),
                ('pickup_city', models.CharField(choices=[('Chandigarh', 'Chandigarh'), ('Delhi', 'Delhi'), ('Amritsar', 'Amritsar'), ('Shimla', 'Shimla'), ('Jammu', 'Jammu'), ('Srinagar', 'Srinagar'), ('Jaipur', 'Jaipur'), ('Manali', 'Manali')], max_length=50)),
                ('drop_city', models.CharField(choices=[('Chandigarh', 'Chandigarh'), ('Delhi', 'Delhi'), ('Amritsar', 'Amritsar'), ('Shimla', 'Shimla'), ('Jammu', 'Jammu'), ('Srinagar', 'Srinagar'), ('Jaipur', 'Jaipur'), ('Manali', 'Manali')], max_length=50)),
                ('pickup_date', models.DateField()),
                ('pickup_time', models.TimeField()),
                ('cab_type', models.CharField(choices=[('sedan', 'Sedan (4 Seater)'), ('suv', 'SUV (6 Seater)'), ('tempo', 'Tempo Traveller (12 Seater)')], max_length=20)),
                ('passengers', models.PositiveIntegerField(default=1)),
                ('trip_type', models.CharField(choices=[('one_way', 'One Way'), ('round_trip', 'Round Trip')], default='one_way', max_length=20)),
                ('return_date', models.DateField(blank=True, null=True)),
                ('estimated_fare', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('commission_rate', models.DecimalField(decimal_places=2, default=15.0, max_digits=5)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('on_trip', 'On Trip'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cabs.driver')),
            ],
        ),
    ]
